### ISSUE TITLE
[Small feature suggestion in tetris-libui] Consider making the preview-next-tetris-block optional

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-libui#10]
Hey Andy,

Please disregard/modify as you wish in regards to the following suggestion.

I just tested tetris on libui; works fine on linux, no bugs that I could see. \o/

On icewm it looks like this:

https://i.imgur.com/H8Kq2dI.png

There is one suggestion I have: make it possible to NOT show the "preview
next tetris block" as a feature, perhaps via the menu on top, where you grouped
other functions, such as "Pause" and so forth.

Rationale for the proposal here: if possible I think it would be nice for users /
players to decide how difficult tetris should be. Offering preview by default
is nice and convenient for new users, but some may want to have a slightly
more challenging tetris, so **not** showing the preview may be useful for
these users / players. On a related note, perhaps it should be possible for
players to determine the number-of-ticks (in other words the starting speed
e. g. how fast the tetris blocks are moving).

If glimmer uses a unified code base for tetris then this perhaps has to be
considered for all tetris variants, to avoid fragmentation of the code base
or usability (e. g. I am NOT suggesting to make this SOLELY confined
to tetris-via-libui, but to how glimmer approaches tetris in general. Tetris
and snake kind of have a demo-purpose for glimmer, I completely
understand that.)

As always please feel free to close the issue at any moment in time! Glimmer
on. \o/

**Comment by AndyObtiva** [comment]
Done in [v0.4.22](https://rubygems.org/gems/glimmer-dsl-libui/versions/0.4.22)

Change Log for v0.4.22:
- examples/tetris.rb "Show Next Block Preview" menu item under "View" menu
- examples/tetris.rb "Speed" menu
- Fix issue with examples/tetris.rb not accelerating upon level ups

[Glimmer Tetris](https://github.com/AndyObtiva/glimmer-dsl-libui#tetris)

![Screen Shot 2022-02-05 at 5 42 29 PM](https://user-images.githubusercontent.com/23052/152661419-1dc221bc-60a0-434c-bf15-a512c21119a0.png)
![Screen Shot 2022-02-05 at 5 42 22 PM](https://user-images.githubusercontent.com/23052/152661418-b2cda1ce-dd33-484b-a23f-2292fd7ff8c1.png)
![Screen Shot 2022-02-05 at 5 42 57 PM](https://user-images.githubusercontent.com/23052/152661420-1086897f-7692-4409-be3a-b6b7926a9f20.png)
![Screen Shot 2022-02-05 at 5 43 06 PM](https://user-images.githubusercontent.com/23052/152661421-680eeb33-2c7f-417f-a8a0-76e5e90ca483.png)
