### ISSUE TITLE
[Small typo in the main README] destorying font

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-libui#13]
The following part:

"Automatically allocate font descriptors upon instantiating font_button controls and free them when destorying font_button controls"

should probably be

"Automatically allocate font descriptors upon instantiating font_button controls and free them when destroying font_button controls"

I think destorying is a typo.

**Comment by AndyObtiva** [comment]
This has been noted and [fixed](https://github.com/AndyObtiva/glimmer-dsl-libui#smart-defaults-and-conventions)!

Thank you for reporting and cheers!
