### ISSUE TITLE
default_font example for non-area?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-libui#14]
Hello,

The draw text example has this:

    default_font family: 'Georgia', size: 13, weight: :medium, italic: :normal, stretch: :normal

This also works, the font looks like Georgia.

I am not sure how to use such a font for, example, a button. Would it be possible to add
some such example? Perhaps ideally many different fonts in the same glimmer-dsl-libui
application?

I'd love to get an application with buttons of larger size; this is to aid an elderly person
with a bad eyesight status.

**Comment by AndyObtiva** [comment]
[This has been answered in the other issue request about button with width and height](https://github.com/AndyObtiva/glimmer-dsl-libui/issues/11?notification_referrer_id=NT_kwDNWgywMjg4NzAwNjUyNToyMzA1Mg#issuecomment-1003483477): https://github.com/AndyObtiva/glimmer-dsl-libui/issues/11?notification_referrer_id=NT_kwDNWgywMjg4NzAwNjUyNToyMzA1Mg#issuecomment-1003483477

Screenshots:

![custom label](https://github.com/AndyObtiva/glimmer-dsl-libui/raw/master/images/glimmer-dsl-libui-windows-area-based-custom-controls-text-label.png)

![custom button](https://github.com/AndyObtiva/glimmer-dsl-libui/raw/master/images/glimmer-dsl-libui-windows-area-based-custom-controls-push-button.png)
