### ISSUE TITLE
Just some info: https://github.com/libui-ng/libui-ng may be a future alternative to andlabs-libui

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-libui#17]
Hi Andy, just a short notification

https://github.com/libui-ng/libui-ng may be a future alternative to andlabs libui. I can not yet say how realistic
it is for these guys to maintain a libui 2.0 but we can always hope for the best. :)

I mention it here just in the case you have some issues you may want to see resolved eventually - perhaps
they can help eventually. Either way this issue request is just a short notification - sorry for spamming the
issue tracker. :D

**Comment by AndyObtiva** [comment]
andlabs has been in the GUI industry a very long time. I would want the next release of libui to come from him.

**Comment by kojix2** [comment]
Hi there!

LibUI will search for shared libraries in the `LIBUIDIR` directory if you set the environment variable `LIBUIDIR`.
https://github.com/kojix2/LibUI/blob/6445605ed1a1626ec8920aa5666d20624ff6c770/lib/libui.rb#L14-L15

Here is how to try libui-ng in Ruby's LibUI.

Build libui-ng: 

```sh
# build
git clone https://github.com/libui-ng/libui-ng
cd libui-ng
meson setup build # options...
ninja -C build
```

Create a symbolic link (remove number)

```sh
cd build/meson-out
ln -s libui.so.0 libui.so # In the case of Linux
```

Then

```ruby
ENV["LIBUIDIR"] = "/home/kojix2/C/libui-ng/build/meson-out" # change here

require "libui"

# check
p LibUI.ffi_lib
# "/home/kojix2/C/libui-ng/build/meson-out"

# Your code goes here...
```
