### ISSUE TITLE
Break apart README into guides?

### ISSUE THREAD

**Issue by baweaver** [AndyObtiva/glimmer-dsl-libui#18]
Noticed that trying to load the README on any mobile device or device without a lot of bandwidth is going to lag out or crash a browser. Would it be possible to segment the README into cross-linked subguides, rather than having the entirety of the information present in it?

**Comment by AndyObtiva** [comment]
@rubyFeedback Just FYI, GitHub already supports a Table of Content feature that lets software engineers jump quickly between sections whether in Desktop or Mobile browsers.

Here is a screenshot of where to find it (I use it all the time; you just gotta click on the list icon on the top-left corner):

![Screen Shot 2022-02-25 at 11 19 38 PM](https://user-images.githubusercontent.com/23052/155828703-e70d88a1-930e-4c7a-bec7-2d5794e143ae.png)
