### ISSUE TITLE
Games for libui? Tetris?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-libui#2]
Heya Andy,

I saw that you have tetris for glimmer-dsl-swt here:

https://github.com/AndyObtiva/glimmer-dsl-swt/blob/v4.18.3.1/samples/elaborate/tetris.rb

I was wondering whether this could be added to libui too.

I think in the simplest way, we could simulate a tetris by having buttons placed
in a grid; and then these buttons may have differential text (even if we may not
be able to use colours; but perhaps we can use unattributed string for colours
there). So the "tetris blocks" would then just be simulated via buttons. Of
course I suppose we could use the drawing area too; you did the circle example,
but I was mostly wondering for a minimal example. (Minimal so as to minimize
time investment to it.)

Actually, I came from the point of view of "would it not be nice if there would be
games in libui", and here I was thinking of simple games, such as tic tac toe,
or snake (where the snake eats an apple and gets bigger on a 2D map).

At any rate, please feel free to ignore/disregard; it's more an idea of "when you
have some time and are bored" then perhaps that could be added to 
glimmer-dsl-libui. Thank you for reading this suggestion either way!

**Comment by AndyObtiva** [comment]
Cool!

I got an initial version of Tetris working (without the scoreboard or menus):
https://github.com/AndyObtiva/glimmer-dsl-libui/blob/development/examples/tetris.rb

![Screen Shot 2021-11-03 at 1 26 02 PM](https://user-images.githubusercontent.com/23052/140153788-6f0c0805-30ff-418b-92d8-7b98fbcf476d.png)

I added the games you mentioned to [TODO.md](https://github.com/AndyObtiva/glimmer-dsl-libui/blob/development/TODO.md) (Tetris, Tic Tac Toe, and Snake)

I will close this issue once I have made releases with these games.

**Comment by AndyObtiva** [comment]
An improved version of Tetris has been released with a bevel-block 3D look:

![3D look](https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-libui/1200bde6b1dee3bdf2ba682f531f42277bd2425d/images/glimmer-dsl-libui-mac-tetris.png)

**Comment by AndyObtiva** [comment]
A version just got released with a score board on top, including a next tetromino preview:

![Tetris with Score Board](https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-libui/84be478abbf8a330a452feeacfff1de5df38b5f2/images/glimmer-dsl-libui-mac-tetris.png)

**Comment by AndyObtiva** [comment]
The Tetris example is done in the latest release. It now has option menus and a high score dialog.

![Tetris High Score Dialog](https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-libui/9ebe4e0de0d44c658609048c083ac8e1b0dbf0a2/images/glimmer-dsl-libui-mac-tetris-high-scores.png)

**Comment by kojix2** [comment]
Wow!

**Comment by AndyObtiva** [comment]
Tic Tac Toe has been implemented and released.

![tic tac toe](https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-libui/cdb2c725779fab20e02cecbc5453fd4d6fc650e0/images/glimmer-dsl-libui-mac-tic-tac-toe.png)

![o wins](https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-libui/cdb2c725779fab20e02cecbc5453fd4d6fc650e0/images/glimmer-dsl-libui-mac-tic-tac-toe-player-o-wins.png)

![x wins](https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-libui/cdb2c725779fab20e02cecbc5453fd4d6fc650e0/images/glimmer-dsl-libui-mac-tic-tac-toe-player-x-wins.png)

![draw](https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-libui/cdb2c725779fab20e02cecbc5453fd4d6fc650e0/images/glimmer-dsl-libui-mac-tic-tac-toe-draw.png)

**Comment by AndyObtiva** [comment]
Snake has been implemented [test-first](https://github.com/AndyObtiva/glimmer-dsl-libui/tree/master/spec/examples/snake/model/game_spec.rb) following the MVP ([Model](https://github.com/AndyObtiva/glimmer-dsl-libui/tree/master/examples/snake/model/game.rb) / [View](https://github.com/AndyObtiva/glimmer-dsl-libui/tree/master/examples/snake.rb) / [Presenter](https://github.com/AndyObtiva/glimmer-dsl-libui/tree/master/examples/snake/presenter/grid.rb)) architectural pattern and released in [v0.2.22](https://rubygems.org/gems/glimmer-dsl-libui/versions/0.2.22).

Snake Screenshot:
![Snake](https://github.com/AndyObtiva/glimmer-dsl-libui/raw/master/images/glimmer-dsl-libui-mac-snake.png)

Snake Game Over Screenshot:
![Snake Game Over](https://github.com/AndyObtiva/glimmer-dsl-libui/raw/master/images/glimmer-dsl-libui-mac-snake-game-over.png)

With that, the issue request is fully addressed.

Happy [Glimmering](https://github.com/AndyObtiva/glimmer)!
