### ISSUE TITLE
Cannot add rows to a table that started empty

### ISSUE THREAD

**Issue by singpolyma** [AndyObtiva/glimmer-dsl-libui#36]
If a table starts bound to an empty array, then adding elements to the array does nothing

**Comment by singpolyma** [comment]
Calling `#clear` right away after `cell_rows` is fine.

**Comment by AndyObtiva** [comment]
Good catch! I just confirmed the issue.

**Comment by AndyObtiva** [comment]
This issue has been fixed with version `0.6.0.pre.2`: 
https://rubygems.org/gems/glimmer-dsl-libui/versions/0.6.0.pre.2

I am closing this issue as a result. If you encounter further related issues, you may comment or re-open if needed.
