### ISSUE TITLE
Add on_click listener to a :text control.

### ISSUE THREAD

**Issue by sergioro9** [AndyObtiva/glimmer-dsl-libui#56]
It seems that :on_click is not available for :text element. Could this be added in future versions? Alternatively, I could use :on_click in a :button but I need the button to look like plain text... I haven't found a button property that can do that.

**Comment by AndyObtiva** [comment]
[Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) actually supports this sort of behavior via general control listeners. All controls in it support `on_mouse_down` for example:

```ruby
window {
  text {
    on_mouse_down do
      message_box {
        text 'Mouse Event'
        message 'Mouse Down'
      }.open
    end
  }
}.show
```

<img width="283" alt="Screenshot 2023-09-01 at 3 32 39 PM" src="https://github.com/AndyObtiva/glimmer-dsl-libui/assets/23052/6cbea12c-f068-4895-94f4-2502c5aa5bb9">

However, Glimmer DSL for LibUI does not support general mouse and keyboard event listeners. Each control has its own unique listeners only.

I just reported the need for supporting general control mouse listeners (and other general listeners) at the upstream libui-ng C library project:
https://github.com/libui-ng/libui-ng/issues/219

Thank you for reporting this. In the meantime, you could try to accomplish your needs using [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) or another [Glimmer GUI toolkit](https://github.com/AndyObtiva/glimmer) that supports the feature you need.

**Comment by cody271** [comment]
> I need the button to look like plain text... I haven't found a button property that can do that.

What about a custom button control with `area` ? Here is an example:

```ruby
require 'glimmer-dsl-libui'

include Glimmer

window('Area Label', 400, 400) {
  area {

    text(161, 40, 100) { # declarative stable text
      string('Click me!') {
        font family: 'Arial', size: (OS.mac? ? 14 : 11)
        color :white
      }
    }

    on_mouse_down do |area_mouse_event|
      msg_box('mouse event', 'mouse down')
    end
  }
}.show
```
![area_label1](https://github.com/AndyObtiva/glimmer-dsl-libui/assets/11763424/d9cf1637-17b7-4156-ba44-d570d8dd2774)
![area_label2](https://github.com/AndyObtiva/glimmer-dsl-libui/assets/11763424/2bd65253-e1ad-46c4-9b38-d59eb7b465af)
