### ISSUE TITLE
The Japanese text is displayed strangely

### ISSUE THREAD

**Issue by junogura** [AndyObtiva/glimmer-dsl-libui#67]
The Japanese text is displayed strangely.

code: 
```
window('こんにちは') {
  area {
    text {
      string("こんにちは\n") {
        font family: 'Osaka', size: 20
        color :white
      }
      string("おはようございます。\n") {
        font family: 'ヒラギノ角ゴシック', size: 20
        color :white
      }
      string("おはようございます。\n") {
        font family: 'Arial', size: 20
        color :white
      }
    }
  }
}.show
```

screenshot:
<img width="195" alt="japanese_text" src="https://github.com/user-attachments/assets/526ce486-ed0d-489c-b24a-6eb57e8bfc1f">

ruby 3.3.5 on macOS 14.6.1

**Comment by AndyObtiva** [comment]
@kojix2 you have used Glimmer DSL for LibUI in Japanese, so you might know how to handle this issue. If there is an issue to report to the upstream project [libui-ng](https://github.com/libui-ng/libui-ng), could you please report it?

BTW, I confirm the issue locally. What is happening is the text in every `string` (attributed string) is getting split between two parts of text. The first part of the text is showing up normally according to the font and color of the attributed `string`. The second part of the text is showing up as black (default color) and in a different front (default font). It seems like the attributed `string` is not getting processed for the full `String` argument that is passed in for some reason. This might be a bug in [libui-ng](https://github.com/libui-ng/libui-ng) in Japanese.

**Comment by junogura** [comment]
I see. I will do that.

**Comment by AndyObtiva** [comment]
Actually, I was talking to @kojix2 because he’s Japanese too. He built the LibUI Ruby binding that is utilized by Glimmer DSL for LibUI. We might run a few tests and verifications first before reporting to libui-ng (the C library utilized by Glimmer DSL for LibUI). 

So, you don’t need to do anything for now @junogura

**Comment by kojix2** [comment]
Hello Andy and Ogura,

I tested this issue. 
At first, I thought it was a problem specific to macOS, but the same issue happened on Ubuntu.  
Then, I considered that the problem might be with Glimmer DSL for LibUI.  
However, the same problem occurred with a C language code that does the same thing.  
I also found that the issue happens in many non-alphabet languages, not just Japanese.

Is this a serious bug?  
I found it might not be. The documentation for `ui.h` says the following:

```c
// uiAttributedStringSetAttribute() sets an attribute in the byte range [start, end)
// of the string s. Any existing attributes in that byte range of the same type are
// removed. The string s takes ownership of the attribute a; you should not use it after
// uiAttributedStringSetAttribute() returns.
_UI_EXTERN void uiAttributedStringSetAttribute(uiAttributedString *s, uiAttribute *a, size_t start, size_t end);
```

> `uiAttributedStringSetAttribute()` sets an attribute in the **byte range** [start, end) of the string `s`.

That is, this function takes a byte range as an argument, not the index when the string is viewed as an array.
In some languages, the number of characters does not match the byte range because some characters use more than one byte, especially in languages with multi-byte encodings like UTF-8.

I think this could be the reason for the issue.

**Comment by kojix2** [comment]
Fork the repository, then

```sh
git clone https://github.com/your_name/glimmer-dsl-libui
ruby -pi -e 'gsub("@string.size", "@string.bytesize")' glimmer-dsl-libui/lib/glimmer/libui/attributed_string.rb
cd glimmer-dsl-libui
git checkout -b bytesize
git commit -m "Use `bytesize` instead of `size` for attribute setting"
git push origin bytesize
```

Then create a pull request.
Not sure if this is enough :man_shrugging:

**Comment by junogura** [comment]
I tried  that chage.
It looks good.
<img width="399" alt="Japanese_Test_2" src="https://github.com/user-attachments/assets/633a01b7-e3e3-48fe-b0d5-2aeec0667914">

But, I couldn't push changes. 
I don't have permission to do this.

> » git push origin bytesize
> ERROR: Permission to AndyObtiva/glimmer-dsl-libui.git denied to junogura.
> fatal: Could not read from remote repository.

**Comment by kojix2** [comment]
@junogura 
You will need to fork the repository first.

![image](https://github.com/user-attachments/assets/9e56b398-3358-4fd2-9f1d-ea3a4257b7cc)

If you are not familiar with GitHub and would like to read the Japanese explanation, the following blog post will be helpful.
[【超図解】OSSにPull Requestを出す時の備忘録](https://qiita.com/y-vectorfield/items/b955617712f3b66359f2)

**Comment by junogura** [comment]
I did it. 
I have used github only personally untill now.

**Comment by AndyObtiva** [comment]
@junogura Thanks a lot for the fix in [PR #68](https://github.com/AndyObtiva/glimmer-dsl-libui/pull/68)! It makes total sense as to why the bug happened. I will test it and merge the code as soon as I have a chance.

**Comment by AndyObtiva** [comment]
@junogura the fix has been tested and released in [glimmer-dsl-libui gem version 0.12.4](https://rubygems.org/gems/glimmer-dsl-libui/versions/0.12.4):
https://rubygems.org/gems/glimmer-dsl-libui/versions/0.12.4

Thank you for the PR.

**Comment by kojix2** [comment]
> git commit -m "Use `bytesize` instead of `size` for attributed setting"

Maybe the commit message should have been "attribute setting" or "attributed string" instead.
Just demonstrating that it's okay if you're not great at English when contributing to OSS. :sweat_smile:

**Comment by AndyObtiva** [comment]
> Maybe the commit message should have been "attribute setting" or "attributed string" instead. My bad.
Just demonstrating that it's okay if you're not great at English when contributing to OSS. 😅

No big deal. I just reworded the commit to `attributed string` while keeping the original author name on it. 

https://github.com/AndyObtiva/glimmer-dsl-libui/commit/06ac9d41ca159fc8e28b2342899990ca20f7fc16
