### ISSUE TITLE
Suggestions for preventing the "exec" icon from showing

### ISSUE THREAD

**Issue by chip** [AndyObtiva/glimmer-dsl-libui#71]
Hi @AndyObtiva,

I was inspired by the article (and your comment) at [Create a MacOS desktop application with pure Ruby (Tutorial)](https://dev.to/josephschito/create-macos-application-desktop-with-pure-ruby-tutorial-36io?utm_source=pocket_shared) and wanted to package my Pathos app, as seen [here *Go version*](https://github.com/chip/pathos) and [here *Ruby version*](https://github.com/chip/pathos.rb), into something available for macOS via the AppStore.

Based on that blog post I eventually ended up with a heavily tweaked [Rakefile](https://gist.github.com/chip/28a68933bc6702cd38e12d80dedc9720). I need to remove some cruft, but it eventually gives me something to allow [Platypus](https://github.com/sveinbjornt/Platypus) to build a macOS app.

However, opening this app shows 2 icons: one that I created for the app, and the other which is the "exec" terminal icon that macOS displays whenever a shell is being executed and there's no icon associated. Application switching (using Cmd+Tab) to the icon I created does give me access to the menus created by glimmer-dsl-libui, which is great, but the application is not shown. To do that, I must application switch over to the "exec" icon.

**Do you have any examples or suggestions for eliminating the "exec" icon as well as showing the app when the icon from my Platypus config is selected?**

P.S. Additional inspiration in issue #65 

Here are some screenshots and details for reference...

1. Pathos macOS (created using glimmer-dsl-libui):
![PathosMacOS](https://github.com/user-attachments/assets/e57eb448-bf9d-49cc-a9ce-95a29d868bd3)

2. Platypus configuration used for creating the "PathosMacOS.app" directory. The *Script Path* points to a package directory created via my [Rakefile](https://gist.github.com/chip/28a68933bc6702cd38e12d80dedc9720). I used `rake package:osx` to create the package directory, **pathos_gui-1.0.0-osx-arm64**:
![PlatypusConfig](https://github.com/user-attachments/assets/afdadc1e-c5fd-45aa-b4b7-cbfe86e60895)

3. The *Script Path* ultimately points to this script:
```bash
#!/bin/bash
set -e

# TODO: update this for each app
APP_ROOT="pathos_gui/launch.rb"

# Figure out where this script is located.
SELFDIR="`dirname \"$0\"`"
SELFDIR="`cd \"$SELFDIR\" && pwd`"

# Tell Bundler where the Gemfile and gems are.
export BUNDLE_GEMFILE="$SELFDIR/lib/vendor/Gemfile"
unset BUNDLE_IGNORE_CONFIG

# Run the actual app using the bundled Ruby interpreter, with Bundler activated.
exec "$SELFDIR/lib/ruby/bin/ruby" -rbundler/setup "$SELFDIR/lib/app/$APP_ROOT"
```

4. Running `open PathosMacOS.app` via the terminal displays the 2 icons.

5. Application switching (via Cmd-Tab) to this icon will show the menus created by glimmer-dsl-lib, but does **not** focus the app:
![PathosMacOSIcon](https://github.com/user-attachments/assets/287f522f-2d82-4f8f-a3a7-74c294cc3b34)

6. Application switching (via Cmd-Tab) to this icon will show the app created with glimmer-dsl-libui (i.e., "put the app in focus"), but is not the icon I use for the app:
![executable_binary](https://github.com/user-attachments/assets/125e5566-3fe3-4c6e-9ced-76ddf44dc857)

**Summary**
I believe the "exec" icon is shown because the *Script Path* points to a `bash` script, which in turn launches the glimmer-dsl-libui app. However, I need some suggestions for launching the glimmer-dsl-lib app directly so that it can include the necessary gems, Traveling Ruby, icons, etc.

Sorry if this was too long. Any suggestions are greatly appreciated. Thanks so much for your effort on this project!

**Comment by AndyObtiva** [comment]
I don't have enough experience with MacOS packaging of Ruby Glimmer-DSL-for-LibUI applications yet to provide an answer to your question. I am sorry. 

I wonder if it is a limitation in Platypus. Maybe, contact them about the issue.

**Comment by chip** [comment]
@AndyObtiva - No worries. I'm going to give either tebako or rubyc a try. Thanks again!

**Comment by AndyObtiva** [comment]
OK, if you get things working another way, please let me know as I'd be interested to learn of alternate ways for packaging CRuby, and might want to document them too in Glimmer DSL for LibUI.
