### ISSUE TITLE
[Small typo in the main readme] - "maintainbility" should probably be "maintainability"

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-libui#9]
Hey there Andy, hope I am not nitpicking too much :D

The part in the README:

    improving productivity and maintainbility immensely

should probably be:

    improving productivity and maintainability immensely

So I think an "a" is missing there.

(I'll also use this opportunity to comment that I am currently rewriting my
third largest project. This was necessary to fix some bugs. There are
also ruby-gtk3, sinatra, and libui specific parts; in the long run I tend
to add glimmer-dsl-libui, largely due to windows support, just to showcase.
But right now I am still bug fixing and working on issues and the rewrite,
so that may take me several days, perhaps even up until middle of
january or so. I have had a few ideas about libui-centric elements, but
I also work through a java swing book right now, so it goes slowly ...
anyway enough off-topic here)

**Comment by AndyObtiva** [comment]
OK, fixed!

Thank you for noting.
